---
title: "Booze and choice of seat"
author: "Put your name here!"
date: "put the date here"
output:
  html_document:
    df_print: paged
---

```{r include=FALSE,echo=FALSE}
require(tidyverse)
require(tigerstats)
data(ucdavis1)
davisgals <- filter(ucdavis1,Sex=="Female")
write.csv(davisgals,file="davisgals")
```

# Introduction

<!--In this section you explain what you are trying to show.  Where did the data come from?  What is the research or other question you are trying to answer?!-->
Is there any difference in alcohol consumption between the students who sit in the front, middle, and back rows at UC Davis.  
  
Same question restricted to just female students. 
  

# Methods

<!--Decide on your methods:  use "variable analysis" or other appropriate descriptors.  Make sure to choose at least one graphical method and at least one numerical method.!-->

#Results

<!--Divide this section into two sub-sections:  One for your descriptive  results and one for your inferential results.!-->

## Descriptive Results

### Graphical Descriptive Results

<!--Graphical results here.  Make sure to show your code.  Provide appropriate labels for axes, giving units if possible, and provide a good title for the graph, too.  Use the graphical results to describe the patterns if any that exist in the data as focused toward the research question!-->
```{r}
boxplot(alcohol~Seat,data=ucdavis1,main="guys & gals")
```
  
```{r}
boxplot(alcohol~Seat,data=davisgals,main="Just gals")
```  

### Numerical Descriptive Results

<!--Numerical results go here. Use the numerical results to describe the patterns if any that exist in the data as focused toward the research question!-->
  
```{r}
summary(alcohol~Seat,data=ucdavis1)
```
   
```{r}
summary(alcohol~Seat,data=davisgals)
```
    
## Inferential Results

<!--State hypothesis clearly.  Make sure your discussion of the inferential test covers all the aspects that the test output produces, such as test statistic, p-value etc.  Make a decision about the null hypothesis, explain the assumptions on which the selected test/procedure was based, and why the chosen procedure satisfys the assumptions and is appropriate to answer the research question!-->
  
```{r}
model <- aov(alcohol~Seat,data=ucdavis1)
summary(model)
plot(TukeyHSD(model))
```
    
```{r}
model.1 <- aov(alcohol~Seat,data=davisgals)
summary(model.1)
plot(TukeyHSD(model.1))
```
  

# Discussion and Conclusion

<!--Discussion and conclusion here.  If you found a relationship be sure to consider whether the relationship occurs because one of the variavbles causes the other, or whether they perhasps are related for some other reason.  Watch the chapter 6 videos from the GeorgeTown videos collection.!-->
